blueprints/interface/models.py
__author__ = 'kj'

from utils.ifmodels import IFModel


class User(IFModel):
    __clct_name__ = 'user'
    __fields__ = ['username', 'password', 'email']


class Stub(IFModel):
    __clct_name__ = 'stub'
    __fields__ = ['type', 'created_by', 'time', 'comments', 'status']


class ClassStub(Stub):
    __initials__ = {'type': 'class'}
    __fields__ = ['name', 'inherited_from', 'metaclass', 'package', 'module']


class FunctionStub(Stub):
    __initials__ = {'type': 'function'}
    __fields__ = ['name', 'returns', 'parameters', 'scope']

blueprints/__init__.py
__author__ = 'kj'

from .interface import interface
from .home import home

blueprints/home/__init__.py
__author__ = 'kj'

from flask import Blueprint
from .controllers import index
import os

home = Blueprint('home', __name__, template_folder="templates")

@home.context_processor
def menu_action():
    return {'action': 'home'}

home.add_url_rule('/', view_func=index)

blueprints/home/controllers.py
__author__ = 'kj'

from flask.views import View, MethodView
from flask import g, render_template

def index():
    g.nav1 = 'home'
    return render_template('home/index.html')

blueprints/interface/__init__.py
__author__ = 'kj'

from flask import Blueprint
from .controllers import *

interface = Blueprint('interface', __name__, template_folder="templates")

@interface.context_processor
def menu_action():
    return {'nav1': 'interface'}

interface.add_url_rule('/', view_func=IndexView.as_view('index'))
interface.add_url_rule('/<id>', view_func=DetailView.as_view('detail'))
interface.add_url_rule('/modules', view_func=ModulesView.as_view('modules'))
interface.add_url_rule('/classes', view_func=ClassesView.as_view('classes'))
interface.add_url_rule('/functions', view_func=FunctionsView.as_view('functions'))
interface.add_url_rule('/<id>/generate_code', view_func=GenerateCodeView.as_view('generate_code'))

blueprints/interface/controllers.py
__author__ = 'kj'

from flask.views import View, MethodView
from flask import g, render_template, jsonify
from bson.objectid import ObjectId
from .models import *
from database import mongo
from utils.ifcodegen import IFCodeGen


class IFInterfaceView:
    def __init__(self):
        g.nav1 = 'interface'
        super().__init__()


class IndexView(MethodView, IFInterfaceView):
    def __init__(self):
        g.nav2 = 'index'
        super().__init__()

    def get(self):
        stubs = list(Stub.query.find())
        return render_template('interface/index.html', stubs=stubs)


class DetailView(MethodView, IFInterfaceView):
    def get(self, id):
        stub = Stub.query.find_one({"_id": ObjectId(id)})
        return render_template('interface/detail.html', stub=stub)


class ModulesView(MethodView, IFInterfaceView):
    def __init__(self):
        g.nav2 = 'modules'
        super().__init__()

    def get(self):
        return render_template('interface/modules.html')

    def post(self):
        pass

    def put(self):
        pass

    def delete(self):
        pass


class ClassesView(MethodView, IFInterfaceView):
    def __init__(self):
        g.nav2 = 'classes'
        super().__init__()

    def get(self):
        return render_template('interface/classes.html')


class FunctionsView(MethodView, IFInterfaceView):
    def __init__(self):
        g.nav2 = 'functions'
        super().__init__()

    def get(self):
        return render_template('interface/functions.html')


class GenerateCodeView(MethodView, IFInterfaceView):
    def get(self):
        return "NIMABI"


class GenerateCodeView(MethodView):
    def get(self, id):
        stub = ClassStub(**Stub.query.find_one({'_id': ObjectId(id)}))
        res = IFCodeGen.gen(stub)
        return jsonify({'title': 'Result', 'body': res})

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}{% if self.title() %} - {% endif %}Interfacade</title>
    <link href="http://cdn.bootcss.com/bootstrap/3.1.1/css/bootstrap-theme.css" rel="stylesheet">
    <link href="http://cdn.bootcss.com/bootstrap/3.1.1/css/bootstrap.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/site.css') }}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    {% block css %}{% endblock %}
</head>
<body>
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('home.index') }}">Interfacade</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li{% if g.nav1 == 'home' %} class="active"{% endif %}><a href="{{ url_for('home.index') }}"><span
                        class="glyphicon glyphicon-home"></span></a></li>
                <li{% if g.nav1 == 'interface' %} class="active"{% endif %}><a
                        href="{{ url_for('interface.index') }}"><span class="glyphicon glyphicon-transfer"></span></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">TODO <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">Nav header</li>
                        <li><a href="#">Separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="../navbar/">Default</a></li>
                <li><a href="../navbar-static-top/">Static top</a></li>
                <li class="active"><a href="./">Fixed top</a></li>
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</div>

<div class="container">
    {% if self.left_menu() %}
        <div class="col-md-3">
            <ul class="nav nav-pills nav-stacked">
                {% block left_menu %}{% endblock %}
            </ul>
        </div>
    {% endif %}
    <div class="{% if self.left_menu() %}col-md-9{% else %}col-md-12{% endif %}">
        {% block body %}
            <!-- Main component for a primary marketing message or call to action -->
            <div class="jumbotron">
                <h1>Navbar example</h1>

                <p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work.
                    It
                    includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>

                <p>To see the difference between static and fixed top navbars, just scroll.</p>

                <p>
                    <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar
                        docs &raquo;</a>
                </p>
            </div>
        {% endblock %}
    </div>
</div>
<!-- /container -->

{% include "parts/ifdialog.html" %}

<script src="http://cdn.bootcss.com/jquery/2.1.1/jquery.js"></script>
<script src="http://cdn.bootcss.com/bootstrap/3.1.1/js/bootstrap.js"></script>
<script src="http://cdn.bootcss.com/angular.js/1.3.0-beta.8/angular.js"></script>
<script src="{{ url_for('static', filename='js/site.js') }}"></script>
{% block script %}{% endblock %}
</body>
</html>

templates/home/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

templates/interface/classes.html
{% extends "interface/subbase.html" %}

Classes

NIMABICAONIMA

templates/interface/detail.html
{% extends "interface/subbase.html" %}

{% block body %}
    <button class="btn btn-success" onclick="generateCode({{ stub.id }})"><span class="glyphicon glyphicon-play"></span> Gen</button>
    <br><br>
    {% for prop, val in stub.items() %}
        <div class="input-group">
            <span class="input-group-addon">{{ prop }}</span>
            <span type="text" class="form-control">{{ val }}</span>
        </div>
        <br>
    {% endfor %}
{% endblock %}

{% block script %}
    <script src="{{ url_for("static", filename="js/interface/detail.js") }}"></script>
    <script type="text/javascript">
        function generateCode(id) {
            ifutil.popUp("{{ url_for('.generate_code', id=stub._id) }}", '');
        }
    </script>
{% endblock %}

templates/interface/functions.html
{% extends "interface/subbase.html" %}

Functions

NIMABICAONIMA

templates/interface/index.html
{% extends "interface/subbase.html" %}

{% block body %}
    {% if stubs %}
        <table class="table table-hover">
            <thead>
            <tr>
                <th>View</th>
                <th>Type</th>
                <th>Name</th>
                <th>Comments</th>
            </tr>
            </thead>
            <tbody>
            {% for stub in stubs %}
                <tr>
                    <td><a class="btn btn-info" href="{{ url_for(".detail", id=stub._id) }}"><span class="glyphicon glyphicon-list"</a></td>
                    <td>{{ stub.type }}</td>
                    <td>{{ stub.name }}</td>
                    <td>
                        {{ stub.comments }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        No stubs yet.
    {% endif %}
{% endblock %}

templates/interface/modules.html
{% extends "interface/subbase.html" %}

{% block body %}
    <form action="{{ url_for(".generate_code") }}" method="post">
        <label for="interface_type">Stub type</label>
        <select id="interface_type" name="interface_type">
            <option value="module">Module</option>
            <option value="class">Class</option>
            <option value="function">Function</option>
            <option value="iterator">Iterator</option>
            <option value="decorator">Decorator</option>
        </select>
    </form>
{% endblock %}

templates/interface/subbase.html
{% extends "base.html" %}

{% block title %}Interfaces{% endblock %}

{% block left_menu %}
    <li{% if g.nav2 == 'index' %} class="active"{% endif %}><a href="{{ url_for('.index') }}">Summary</a></li>
    <li><strong>Stubs</strong></li>
    <li{% if g.nav2 == 'modules' %} class="active"{% endif %}><a href="{{ url_for('.modules') }}">Modules</a></li>
    <li{% if g.nav2 == 'classes' %} class="active"{% endif %}><a href="{{ url_for('.classes') }}">Classes</a></li>
    <li{% if g.nav2 == 'functions' %} class="active"{% endif %}><a href="{{ url_for('.functions') }}">Functions</a></li>
{% endblock %}

{% block body %}
{% endblock %}

templates/parts/ifdialog.html
<div class="modal fade" ifdialog>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" title></h4>
      </div>
      <div class="modal-body">
        <pre body></pre>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->